name: Run scrape site for search
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
jobs:
  run-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: scrape site for Algolia search
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/fkviking/bot-doc-scrape/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"master"}'
        env:
          TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
