name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/
    - name: scrape site for Algolia search
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/fkviking/bot-doc-scrape/actions/workflows/main.yml/dispatches" \
          -d '{"ref":"master"}'
      env:
        TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
